[tool.poetry]
name = "testing-rust-integration"
version = "0.1.0"
description = ""
authors = ["intezya <intezya@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
