[package]
name = "test_module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "test_module"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
num-bigint = "0.4.6"
